#!/usr/bin/env sh

# bar settings
yabai -m config status_bar                   on
yabai -m config status_bar_text_font         "Helvetica Neue:Bold:12.0"
yabai -m config status_bar_icon_font         "Font Awesome 5 Free:Solid:12.0"
yabai -m config status_bar_background_color  0xff21232e
yabai -m config status_bar_foreground_color  0xffa8a8a8
yabai -m config status_bar_space_icon_strip             
yabai -m config status_bar_power_icon_strip   
yabai -m config status_bar_space_icon        
yabai -m config status_bar_clock_icon        

# global settings
yabai -m config mouse_follows_focus          off
yabai -m config focus_follows_mouse          on
yabai -m config window_placement             second_child
yabai -m config window_topmost               off
yabai -m config window_opacity               on
yabai -m config window_opacity_duration      0.0
yabai -m config window_shadow                on
yabai -m config window_border                on
yabai -m config window_border_placement      inset
yabai -m config window_border_width          4
yabai -m config window_border_radius         1.0
yabai -m config active_window_border_topmost off
yabai -m config active_window_border_color   0xff21232e
yabai -m config normal_window_border_color   0xff505050
yabai -m config insert_window_border_color   0xffd75f5f
yabai -m config active_window_opacity        1.0
yabai -m config normal_window_opacity        0.90
yabai -m config split_ratio                  0.50
yabai -m config auto_balance                 off
yabai -m config mouse_modifier               fn
yabai -m config mouse_action1                move
yabai -m config mouse_action2                resize

# general space settings
yabai -m config layout                       bsp
yabai -m config top_padding                  0
yabai -m config bottom_padding               0
yabai -m config left_padding                 0
yabai -m config right_padding                0
yabai -m config window_gap                   0

# assign apps to the particular spaces
yabai -m rule --add app="Code" space=3
yabai -m rule --add app="Alacritty" space=4
yabai -m rule --add app="Rambox" space=5
yabai -m rule --add app="^Spotify$" space=6 native-fullscreen="on"

# disable yabai for particular apps
yabai -m rule --add app="System Preferences" manage=off
yabai -m rule --add app="Bitwarden" manage=off grid=6:4:1:1:2:4
yabai -m rule --add app="AnyConnect" manage=off

# perfectly center floated, nonresizable apps
events=('application_launched')
apps=('System Preferences' 'AnyConnect')

read -r -d '' action <<- 'EOF'
  window="$(yabai -m query --windows --window)"
  display="$(yabai -m query --displays --window)"
  coords="$(jq \
    --argjson window "${window}" \
    --argjson display "${display}" \
    -nr '(($display.frame | .x + .w / 2) - ($window.frame.w / 2) | tostring)
      + ":"
      + (($display.frame | .y + .h / 2) - ($window.frame.h / 2) | tostring)')"
  yabai -m window --move "abs:${coords}"
EOF

(( ${#apps[@]} ))   && app_query="app=\"^($(IFS=\|;echo "${apps[*]}"))\$\""
for event in "${events[@]}"; do
  yabai -m signal --add label="${0}_signal_${event}" event="${event}" \
    $(eval "${app_query}}") action="${action}"
done


# assign Electron to a 2nd space
yabai -m rule --add app="^Electron$" space=2
